apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-subscription
spec:
  topic: orders
  routes:
    default: /orders/default
    rules:
      - match: event.type == order-completed" 
        path: /orders/completed
      - match: event.type == "order-cancelled"
        path: /orders/cancelled
      - match: event.type == "order-created"
        path: /orders/created
  pubsubname: pubsub
